### ISSUE TITLE
HTTPS Redirect

### ISSUE THREAD

**Issue by FrontEndCoffee** [liquidpineapple/liquidpineapple#75]
fix .htaccess so users get redirected if nog connected using https

**Comment by Fastjur** [comment]
This should / is handled in cloudflare. All traffic is routed to https using a wildcard page rule.

**Comment by FrontEndCoffee** [comment]
The thing is, it doesn't work. I say we try out if modifying the htaccess anyway.. #80

**Comment by FrontEndCoffee** [comment]
<img width="971" alt="screen shot 2017-03-21 at 11 17 01 am" src="https://cloud.githubusercontent.com/assets/16303480/24142778/ef6aea9c-0e27-11e7-9d41-d04be29f64a8.png">

@Fastjur ?

**Comment by FrontEndCoffee** [comment]
> **Fastjur said:**
> This should / is handled in cloudflare. All traffic is routed to https using a wildcard page rule.

<img width="968" alt="screen shot 2017-03-21 at 11 19 47 am" src="https://cloud.githubusercontent.com/assets/16303480/24142922/57a4e914-0e28-11e7-9d5e-97315117b0ea.png">

^ I think you meant this, it's disabled..

**Comment by FrontEndCoffee** [comment]
I enabled it and it works.
